# Generated by Django 4.2.30 on 2026-05-20 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_situation', models.CharField(choices=[('house', 'House with yard'), ('condo', 'Condo / Apartment'), ('townhouse', 'Townhouse'), ('other', 'Other')], default='house', max_length=20)),
                ('other_pets', models.CharField(choices=[('none', 'No other pets'), ('dogs', 'Yes — dogs'), ('cats', 'Yes — cats'), ('multiple', 'Yes — multiple')], default='none', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Awaiting Reply'), ('replied', 'Replied'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=10)),
                ('condition', models.CharField(choices=[('stray', 'Stray / Wandering'), ('injured', 'Injured'), ('sick', 'Sick / Ill'), ('abandoned', 'Abandoned')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responding', 'Responding'), ('rescued', 'Rescued'), ('under_observation', 'Under Observation'), ('in_treatment', 'Recovering'), ('ready_for_adoption', 'Ready for Adoption'), ('adopted', 'Adopted'), ('closed', 'Closed')], default='pending', max_length=25)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High Priority'), ('critical', 'Critical / Emergency')], default='normal', max_length=10)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animal_photos/')),
                ('response_notes', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='RescuedAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Shelter name given to the animal', max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('approx_age', models.CharField(blank=True, help_text='e.g. ~2 yrs, 6 months', max_length=30)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('observation', 'Under Observation'), ('recovering', 'Recovering'), ('adoption', 'Ready for Adoption'), ('adopted', 'Adopted')], default='observation', max_length=15)),
                ('vaccination', models.CharField(choices=[('none', 'Not Vaccinated'), ('partial', 'Partial'), ('complete', 'Fully Vaccinated')], default='none', max_length=10)),
                ('shelter', models.CharField(blank=True, help_text='Shelter / kennel location', max_length=100)),
                ('medical_notes', models.TextField(blank=True)),
                ('temperament', models.CharField(blank=True, help_text='e.g. Gentle, Playful, Shy', max_length=255)),
                ('adoption_open', models.BooleanField(default=False, help_text='Toggle to show in adoption listings')),
                ('rescued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rescued_at'],
            },
        ),
        migrations.CreateModel(
            name='RescueOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reporter', 'Reporter'), ('rescue_org', 'Rescue Organization'), ('admin', 'Admin')], default='reporter', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.rescueorganization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RescuedAnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rescued_animal_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.rescuedanimal')),
            ],
        ),
        migrations.AddField(
            model_name='rescuedanimal',
            name='rescue_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescued_animals', to='core.rescueorganization'),
        ),
        migrations.AddField(
            model_name='rescuedanimal',
            name='source_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescued_animal', to='core.animalreport'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rescue_update', 'Rescue Update'), ('org_reply', 'Organization Reply'), ('adoption_ready', 'Adoption Ready'), ('report_seen', 'Report Seen'), ('report_closed', 'Report Closed'), ('new_inquiry', 'New Inquiry'), ('new_report', 'New Report')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rescuedanimal')),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adoptioninquiry')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.animalreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.rescuedanimal')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.animalreport')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('update', 'Rescue Update'), ('urgent', 'Urgent Rescue Need'), ('adoption', 'Adoption Announcement'), ('missing', 'Missing Pet Alert')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('rescue_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.rescueorganization')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.animalreport')),
            ],
        ),
        migrations.AddField(
            model_name='animalreport',
            name='rescue_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='core.rescueorganization'),
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.rescuedanimal'),
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='rescue_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.rescueorganization'),
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavedAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.rescuedanimal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_animals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'animal')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='adoptioninquiry',
            unique_together={('user', 'animal')},
        ),
    ]
