# Generated by Django 6.0.6 on 2026-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('rescue_update', 'Rescue Update'), ('org_reply', 'Organization Reply'), ('new_user_message', 'New User Message'), ('adoption_ready', 'Adoption Ready'), ('report_seen', 'Report Seen'), ('report_closed', 'Report Closed'), ('new_inquiry', 'New Inquiry'), ('new_report', 'New Report')], max_length=20),
        ),
    ]
