# Generated by Django 4.2.30 on 2026-07-04 02:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescuedAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Shelter name given to the animal', max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('approx_age', models.CharField(blank=True, help_text='e.g. ~2 yrs, 6 months', max_length=30)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('observation', 'Under Observation'), ('recovering', 'Recovering'), ('adoption', 'Ready for Adoption'), ('adopted', 'Adopted')], default='observation', max_length=15)),
                ('vaccination', models.CharField(choices=[('none', 'Not Vaccinated'), ('partial', 'Partial'), ('complete', 'Fully Vaccinated')], default='none', max_length=10)),
                ('shelter', models.CharField(blank=True, help_text='Shelter / kennel location', max_length=100)),
                ('medical_notes', models.TextField(blank=True)),
                ('temperament', models.CharField(blank=True, help_text='e.g. Gentle, Playful, Shy', max_length=255)),
                ('adoption_open', models.BooleanField(default=False, help_text='Toggle to show in adoption listings')),
                ('rescued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rescue_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescued_animals', to='organizations.rescueorganization')),
                ('source_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescued_animal', to='reports.animalreport')),
            ],
            options={
                'ordering': ['-rescued_at'],
            },
        ),
        migrations.CreateModel(
            name='RescuedAnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rescued_animal_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.rescuedanimal')),
            ],
        ),
    ]
