# Generated by Django 6.0.6 on 2026-07-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueorganization',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rescueorganization',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
