# Generated by Django 4.2.30 on 2026-07-07 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_message_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.adoptioninquiry'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('rescue_update', 'Rescue Update'), ('org_reply', 'Organization Reply'), ('new_user_message', 'New User Message'), ('adoption_ready', 'Adoption Ready'), ('report_seen', 'Report Seen'), ('report_closed', 'Report Closed'), ('new_inquiry', 'New Inquiry'), ('new_report', 'New Report'), ('inquiry_status_updated', 'Inquiry Status Updated')], max_length=30),
        ),
    ]
