# Generated by Django 4.2.30 on 2026-07-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_conversation_inquiry_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptioninquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting Reply'), ('replied', 'Replied'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=10),
        ),
    ]
