# Generated by Django 4.2.30 on 2026-07-04 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=10)),
                ('condition', models.CharField(choices=[('stray', 'Stray / Wandering'), ('injured', 'Injured'), ('sick', 'Sick / Ill'), ('abandoned', 'Abandoned')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responding', 'Responding'), ('rescued', 'Rescued'), ('under_observation', 'Under Observation'), ('in_treatment', 'Recovering'), ('ready_for_adoption', 'Ready for Adoption'), ('adopted', 'Adopted'), ('closed', 'Closed')], default='pending', max_length=25)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High Priority'), ('critical', 'Critical / Emergency')], default='normal', max_length=10)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animal_photos/')),
                ('response_notes', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('rescue_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='organizations.rescueorganization')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.animalreport')),
            ],
        ),
    ]
